language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install requests
  - pip install newick
notifications:
  email:
    recipients:
      - abusalehmdtayeen@gmail.com
    on_success: change
    on_failure: always
script:
- python -m unittest discover -s tests -p 'test_*.py' --verbose
